### ISSUE TITLE
SnsTokenResponse类少了unionid属性

### ISSUE THREAD

**Issue by kylinshaw** [vioao/wechat-sdk#2]
使用SnsApi.oauth2AccessToken，我其实是想要unionid，openid都无所谓，开放平台里面应用太多，没有unionid玩不了。

**Comment by victorymakes** [comment]
[代公众号发起网页授权](https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419318590&token=&lang=zh_CN)
文档中并没有对应的unionid说明。需要自己关联
